# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xls-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gta4xlswifi gta4xls,$(TARGET_DEVICE)),)

endif
