# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xls-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta4xls-common

PRODUCT_COPY_FILES += \
    vendor/samsung/gta4xls-common/proprietary/recovery/root/vendor/firmware/hx83102e_gta4xls.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/hx83102e_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/recovery/root/vendor/firmware/w9021_gta4xls.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/w9021_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/bin/hw/gps.sh:$(TARGET_COPY_OUT_VENDOR)/bin/hw/gps.sh \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/teegris_v4.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris_v4.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140_common.hcf \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/mx140_t.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140_t.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/mx140_t_wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140_t_wlan.hcf \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/mx140_t_wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140_t_wlan_t.hcf \
    vendor/samsung/gta4xls-common/proprietary/vendor/etc/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/slsi_reg_database.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/APDV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDV_AUDIO_SLSI.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/APSV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APSV_AUDIO_SLSI.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/OD_V2.1.6_01_26_QVGA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.1.6_01_26_QVGA.nnc \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/OD_V2.3.7_02_05_VGA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.3.7_02_05_VGA.nnc \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/SetMultiCalInfo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SetMultiCalInfo.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/dbmd8_va_asrp_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_asrp_fw.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/dbmd8_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_fw.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/dual_cal_wide_swide.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dual_cal_wide_swide.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/hx83102e_gta4xls.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/is_lib.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/is_rta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/is_rta.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/lmecpu_GC5035.json:$(TARGET_COPY_OUT_VENDOR)/firmware/lmecpu_GC5035.json \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/lmecpu_S5K4HA.json:$(TARGET_COPY_OUT_VENDOR)/firmware/lmecpu_S5K4HA.json \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/rxse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rxse.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/sectiongraph_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.conf \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/setfile_4ha.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_4ha.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/setfile_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gc5035.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/tfa9878.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa9878.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/txse1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse1.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor/firmware/w9021_gta4xls.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/w9021_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor_ramdisk/vendor/firmware/hx83102e_gta4xls.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/hx83102e_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/vendor_ramdisk/vendor/firmware/w9021_gta4xls.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/w9021_gta4xls.bin

PRODUCT_PACKAGES += \
    libGLES_mali \
    gatekeeper.s5e8825 \
    vulkan.mali \
    libsecnativefeature \
    libsecril-client.s5e8825 \
    libteecl \
    libuuid \
    sensors.grip \
    sensors.inputvirtual \
    sensors.sensorhub \
    libprofileparamstorage \
    libsecaudiocoreutils \
    libspatializerparamstorage \
    android.hardware.gnss@2.1-impl \
    camera.s5e8825 \
    vendor.samsung.hardware.gnss@2.1-impl \
    libMERTA \
    libc++_shared \
    libengmode_client \
    libexynoscamera_merta_plugin \
    libexynoscamera_plugin \
    libexynoscamera_swlme_plugin \
    libexynoscamera_vpl_plugin \
    libhwjsqz \
    liblmecpu \
    libsec2lsi_conversion \
    libsensorlistener \
    libskeymint10device \
    libskeymint_cli \
    libswlme \
    libuniapi \
    libuniplugin \
    libwrappergps \
    libwvhidl \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.1 \
    vendor.samsung.hardware.keymint-V1-ndk_platform \
    vendor.samsung.hardware.thermal@1.0 \
    manifest_android.hardware.drm@1.4-service.widevine \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.security.keymint-service.samsung \
    gpsd \
    vendor.samsung.hardware.gnss@2.1-service \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    libGLES_mali_libOpenCL_symlink32 \
    libGLES_mali_libOpenCL.so_symlink32 \
    libGLES_mali_libOpenCL.so.1_symlink32 \
    libGLES_mali_libOpenCL_symlink64 \
    libGLES_mali_libOpenCL.so_symlink64 \
    libGLES_mali_libOpenCL.so.1_symlink64
