# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xls-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta4xls-common

PRODUCT_COPY_FILES += \
    vendor/samsung/gta4xls-common/proprietary/recovery/root/vendor/firmware/hx83102e_gta4xls.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/hx83102e_gta4xls.bin \
    vendor/samsung/gta4xls-common/proprietary/recovery/root/vendor/firmware/w9021_gta4xls.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/w9021_gta4xls.bin
